# Generated by Django 4.0.6 on 2022-07-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_user_billproduct_customer_product_products'),
        ('users', '0006_userqueuing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQueuing',
            new_name='UserQueue',
        ),
    ]
