# Generated by Django 4.0.6 on 2022-07-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_userqueuing_userqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Management', 'مدیریت'), ('Marketing', 'فروش و بازاریابی'), ('Support', 'پشتیبانی'), ('Complains', 'شکایات'), ('Suggestions', 'انتقادات و پیشنهادات')], default='Suggestions', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Closed', 'بسته شده'), ('Pending', 'در حال بررسی'), ('Waiting', 'در انتظار بررسی')], default='Waiting', max_length=30)),
                ('text', models.TextField(max_length=20000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
