# Generated by Django 4.0.6 on 2022-07-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_country_user_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
