# Generated by Django 4.0.6 on 2022-07-23 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_country_remove_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentNotifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='notification',
            field=models.ManyToManyField(related_name='types', to='users.notification'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
