# Generated by Django 4.0.6 on 2022-08-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_alter_product_user'),
        ('users', '0015_turn_delete_userqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turn',
            name='coworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdTurns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turn',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='bills.product'),
        ),
    ]
