# Generated by Django 4.0.6 on 2022-09-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_requestlog_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='writer',
        ),
    ]
