# Generated by Django 4.0.6 on 2022-07-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_delivery_date_alter_bill_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billproduct',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='products',
            field=models.ManyToManyField(through='bills.BillProduct', to='bills.bill'),
        ),
    ]
