# Generated by Django 4.0.6 on 2022-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rename_products_product_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bills',
        ),
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(through='bills.BillProduct', to='bills.product'),
        ),
    ]
