# Generated by Django 4.0.6 on 2022-07-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_remove_product_bills_bill_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billproduct',
            old_name='customer',
            new_name='seller',
        ),
    ]
